### PR TITLE
Use case insensitive HTTP Headers

### LINKED ISSUE #34: Location vs location
Hi, your library is helping lot of us. There a new problem recent introduced by Vimeo explained below.

There is both spelling of location under json response of endUploadVideo. Can we make this small correction on our code base.

I can create a pull request for the same. If you would like. Attached both version of response in this.

Thanks for all the help in advance.

Location L

location with small L

### PR DESCRIPTION
**Pull request by aaronm67**
Fixes #34 - HTTP Headers are not [case sensitive](https://datatracker.ietf.org/doc/html/rfc2616#section-4.2), and are subject to change at any time. This converts headers to lowercase and changes checks against them to lowercase.

### CODE REVIEW

**Comment by tmendici** [comment]
Hi Aaron,

Today we will publish a new version,

Thanks for your contribute,
Tonino.

**Comment by mathieu-maury** [comment]
Hi !
Any news about the new version publication ?
Thanks

**Comment by VexxTech** [comment]
Hello,

Is there any movement on this new library version? The location issue is becoming a persistent problem with the current version of the library.

**Comment by TopEngineer0926** [comment]
Hi
Any news about the new version publication ?

**Comment by tmendici** [comment]
Hi,
We will publish a new version this evening or tomorrow morning.

Tonino.

**Comment by tmendici** [comment]
Hi,
We will publish a new version this evening or tomorrow morning.

Tonino.

**Comment by TopEngineer0926** [comment]
Please let me know when you can merge it to main.
Thanks.

**Comment by TopEngineer0926** [comment]
Hello @tmendici 
When can you publish this? Could you please let me know it?

**Comment by TopEngineer0926** [comment]
Hello @tmendici 
Any news on update?

**Comment by TopEngineer0926** [comment]
Hi !
Any news about the new version publication ?
Thanks

**Comment by tmendici** [comment]
We have upgraded to Vimeo API 3.4 and this problem no longer exists

**Comment by aaronm67** [comment]
@tmendici Please know, this will break in the future, and even now, will break depending on what infrastructure it hits.

Vimeo does not guarantee the case sensitivity of these headers, and this is something that will change often and without notice.

**Comment by TopEngineer0926** [comment]
Thanks for your update!

**Pull request closed without merging**
